ASP.NET Core/RazorPagesDemo/Controllers/NomenclaturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Cafe.Models;
using RazorPagesDemo.Data;

namespace RazorPagesDemo.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class NomenclaturesController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public NomenclaturesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Nomenclatures
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Nomenclature>>> GetNomenclature(int? skip,int? take, string? orderby)
        {
            return await _context.Nomenclature.ToListAsync();
        }

        // GET: api/Nomenclatures/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Nomenclature>> GetNomenclature(int id)
        {
            var nomenclature = await _context.Nomenclature.FindAsync(id);

            if (nomenclature == null)
            {
                return NotFound();
            }

            return nomenclature;
        }

        // PUT: api/Nomenclatures/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutNomenclature(int id, Nomenclature nomenclature)
        {
            if (id != nomenclature.Id)
            {
                return BadRequest();
            }

            _context.Entry(nomenclature).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!NomenclatureExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Nomenclatures
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Nomenclature>> PostNomenclature(Nomenclature nomenclature)
        {
            _context.Nomenclature.Add(nomenclature);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetNomenclature", new { id = nomenclature.Id }, nomenclature);
        }

        // DELETE: api/Nomenclatures/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteNomenclature(int id)
        {
            var nomenclature = await _context.Nomenclature.FindAsync(id);
            if (nomenclature == null)
            {
                return NotFound();
            }

            _context.Nomenclature.Remove(nomenclature);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool NomenclatureExists(int id)
        {
            return _context.Nomenclature.Any(e => e.Id == id);
        }
    }
}

ASP.NET Core/RazorPagesDemo/Pages/Nomenclatures/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Cafe.Models;
using RazorPagesDemo.Data;

namespace RazorPagesDemo.Pages.Nomenclatures
{
    public class CreateModel : PageModel
    {
        private readonly RazorPagesDemo.Data.ApplicationDbContext _context;

        public CreateModel(RazorPagesDemo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Nomenclature Nomenclature { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Nomenclature.Add(Nomenclature);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ASP.NET Core/RazorPagesDemo/Pages/Nomenclatures/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Cafe.Models;
using RazorPagesDemo.Data;

namespace RazorPagesDemo.Pages.Nomenclatures
{
    public class DeleteModel : PageModel
    {
        private readonly RazorPagesDemo.Data.ApplicationDbContext _context;

        public DeleteModel(RazorPagesDemo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Nomenclature Nomenclature { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nomenclature = await _context.Nomenclature.FirstOrDefaultAsync(m => m.Id == id);

            if (nomenclature == null)
            {
                return NotFound();
            }
            else
            {
                Nomenclature = nomenclature;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nomenclature = await _context.Nomenclature.FindAsync(id);
            if (nomenclature != null)
            {
                Nomenclature = nomenclature;
                _context.Nomenclature.Remove(Nomenclature);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ASP.NET Core/RazorPagesDemo/Pages/Nomenclatures/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Cafe.Models;
using RazorPagesDemo.Data;

namespace RazorPagesDemo.Pages.Nomenclatures
{
    public class DetailsModel : PageModel
    {
        private readonly RazorPagesDemo.Data.ApplicationDbContext _context;

        public DetailsModel(RazorPagesDemo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Nomenclature Nomenclature { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nomenclature = await _context.Nomenclature.FirstOrDefaultAsync(m => m.Id == id);
            if (nomenclature == null)
            {
                return NotFound();
            }
            else
            {
                Nomenclature = nomenclature;
            }
            return Page();
        }
    }
}

ASP.NET Core/RazorPagesDemo/Pages/Nomenclatures/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cafe.Models;
using RazorPagesDemo.Data;

namespace RazorPagesDemo.Pages.Nomenclatures
{
    public class EditModel : PageModel
    {
        private readonly RazorPagesDemo.Data.ApplicationDbContext _context;

        public EditModel(RazorPagesDemo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Nomenclature Nomenclature { get; set; } = default!;

        //OnGet[Filter]Async
        public async Task<IActionResult> OnGetFilterAsync(int? id) // /Nomenclatures?handle=Filter
        {
            return Page();
        }

        //OnGet
        //OnGetAsync

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nomenclature =  await _context.Nomenclature.FirstOrDefaultAsync(m => m.Id == id);
            if (nomenclature == null)
            {
                return NotFound();
            }
            Nomenclature = nomenclature;
            return Page();
        }


        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ModelState.AddModelError("Nomenclature.Name", "Просто так бакенд не пропускає"); // 2 слова/унікальність/ Пиво Чернігівське  = Чернігівське пиво


            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Nomenclature).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!NomenclatureExists(Nomenclature.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool NomenclatureExists(int id)
        {
            return _context.Nomenclature.Any(e => e.Id == id);
        }
    }
}

ASP.NET Core/RazorPagesDemo/Pages/Nomenclatures/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Cafe.Models;
using RazorPagesDemo.Data;
using System.Text.Unicode;
using System.Text;
using Microsoft.AspNetCore.Identity;
using RazorPagesDemo.Services;

namespace RazorPagesDemo.Pages.Nomenclatures
{
    public class IndexModel : PageModel
    {
        internal record NomenclatureR(int id,string name,string price);
        private readonly RazorPagesDemo.Data.ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMyLogger _logger;

        public IndexModel(RazorPagesDemo.Data.ApplicationDbContext context, UserManager<ApplicationUser> userManager,IMyLogger logger)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
        }

        public IList<Nomenclature> Nomenclature { get;set; } = default!;


        public int LinesPerPage { get; set; } = 12;


        [BindProperty(SupportsGet = true)]
        public int CurrentPage { get; set; } = 1;

        public int Pages { get; set; }
        public int Count { get; set; }

        [BindProperty(SupportsGet =true)]
        public string Filter { get; set; }=string.Empty;

        [BindProperty]
        public IFormFile Upload { get; set; }=default!;
        public async Task OnGetAsync()
        {
            var userId = User.GetUserId();

            _logger.Info($"User {userId} get ...");

            var user = await _userManager.GetUserAsync(User);

            var g =new Guid(); // GUID 
            // для баз даних      UUID є унікальним для таблиці (для первинного ключа)

            //Nomenclature = await _context.Nomenclature.Where(f=>f.Name.Contains(Filter ?? string.Empty))
            //                                          .OrderBy(o=>o.Id).Skip((CurrentPage -1)*LinesPerPage).Take(LinesPerPage).ToListAsync();
            //Count = await _context.Nomenclature.Where(f => f.Name.Contains(Filter ?? string.Empty)).CountAsync();
            var query = _context.Nomenclature.AsQueryable();
            if (!string.IsNullOrWhiteSpace(Filter))
            {
                query = query.Where(f => f.Name.Contains(Filter));
            }
            Nomenclature =await query.OrderBy(o => o.Id).Skip((CurrentPage - 1) * LinesPerPage).Take(LinesPerPage).ToListAsync();
            Count = await query.CountAsync();

            Pages = Count/LinesPerPage + ((Count % LinesPerPage) == 0?0:1);


        }

        public async Task OnPostAsync()
        {
            using (var memoryStream = new MemoryStream())
            {
                await Upload.CopyToAsync(memoryStream);
                var str = Encoding.UTF8.GetString(memoryStream.ToArray());
                var nomenclatures = System.Text.Json.JsonSerializer.Deserialize<NomenclatureR[]>(str);
                foreach (var item in nomenclatures)
                {
                    var nomenclature = new Nomenclature { Id = item.id, Name = item.name ,Price = double.Parse(item.price.Replace('.',','))};

                    await _context.Nomenclature.AddAsync(nomenclature);
                }
               
                await _context.SaveChangesAsync();

            }
            Nomenclature = await _context.Nomenclature.Where(f => f.Name.Contains(Filter ?? string.Empty)).ToListAsync();
        }


        public void Clean()
        {

        }
    }
}

ASP.NET Core/RazorPagesDemo/Pages/UserTasks/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using RazorPagesDemo.Data;
using RazorPagesDemo.Services;

namespace RazorPagesDemo.Pages.UserTasks
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly RazorPagesDemo.Data.ApplicationDbContext _context;

        public CreateModel(RazorPagesDemo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            UserTask task = new UserTask();
            task.UserId = User.GetUserId();
            return Page();
        }

        [BindProperty]
        public UserTask UserTask { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (UserTask.UserId != User.GetUserId())
            {
                return NotFound();
            }
            _context.UserTasks.Add(UserTask);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ASP.NET Core/RazorPagesDemo/Pages/UserTasks/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorPagesDemo.Data;
using RazorPagesDemo.Services;

namespace RazorPagesDemo.Pages.UserTasks
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly RazorPagesDemo.Data.ApplicationDbContext _context;

        public DeleteModel(RazorPagesDemo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public UserTask UserTask { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usertask = await _context.UserTasks.FirstOrDefaultAsync(m => m.Id == id);

            if (usertask == null)
            {
                return NotFound();
            }
            else
            {
                UserTask = usertask;
            }

            if (UserTask.UserId != User.GetUserId())
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usertask = await _context.UserTasks.FindAsync(id);
            if (usertask != null)
            {
                UserTask = usertask;
                if (UserTask.UserId != User.GetUserId())
                {
                    return NotFound();
                }

                _context.UserTasks.Remove(UserTask);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ASP.NET Core/RazorPagesDemo/Pages/Nomenclatures/Create.cshtml
@page
@model RazorPagesDemo.Pages.Nomenclatures.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Nomenclature</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nomenclature.Name" class="control-label"></label>
                <input asp-for="Nomenclature.Name" class="form-control" />
                <span asp-validation-for="Nomenclature.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nomenclature.Price" class="control-label"></label>
                <input asp-for="Nomenclature.Price" class="form-control" />
                <span asp-validation-for="Nomenclature.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.NET Core/RazorPagesDemo/Pages/Nomenclatures/Delete.cshtml
@page
@model RazorPagesDemo.Pages.Nomenclatures.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Nomenclature</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nomenclature.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nomenclature.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nomenclature.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nomenclature.Price)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Nomenclature.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

ASP.NET Core/RazorPagesDemo/Pages/Nomenclatures/Details.cshtml
@page
@model RazorPagesDemo.Pages.Nomenclatures.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Nomenclature</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nomenclature.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nomenclature.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nomenclature.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nomenclature.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Nomenclature.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

ASP.NET Core/RazorPagesDemo/Pages/Nomenclatures/Edit.cshtml
@page
@model RazorPagesDemo.Pages.Nomenclatures.EditModel

@{
    ViewData["Title"] = "Edit";
    
}

<h1>Edit</h1>

<h4>Nomenclature</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Nomenclature.Id" />
            <div class="form-group">
                <label asp-for="Nomenclature.Name" class="control-label"></label>
                <input asp-for="Nomenclature.Name" class="form-control" />
                <span asp-validation-for="Nomenclature.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nomenclature.Price" class="control-label"></label>
                <input asp-for="Nomenclature.Price" class="form-control" />
                <span asp-validation-for="Nomenclature.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a  asp-page-handler="Filter">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.NET Core/RazorPagesDemo/Pages/Nomenclatures/Index.cshtml
@page
@model RazorPagesDemo.Pages.Nomenclatures.IndexModel

@{
    ViewData["Title"] = "Index";
    Model.Clean();
}

<h1>Index</h1>


<div class="row">
    <div class="col">
        <a class="btn btn-primary" asp-page="Create">Create New</a>
    </div>
    <div class="col">
        <form method="get">
            Name: <input type="text" name="filter" value="@Model.Filter" />
            <input type="submit" value="Filter" class="btn btn-primary" />
        </form>
    </div>
</div>
<form method="post" enctype="multipart/form-data">
    <input type="file" asp-for="Upload" />  
    <input type="submit"/>

</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nomenclature[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nomenclature[0].Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Nomenclature) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<ul class="pagination">
    @for(int i = 1; i <= Model.Pages; i++)
    {
        <li class="page-item @(i==Model.CurrentPage?"active":"")"><a class="page-link" asp-route-CurrentPage="@i">@i</a></li>
    }
</ul>